### ISSUE TITLE
Logging of output

### ISSUE THREAD

**Issue by redrocketgt** [scavicchio/Easy-Walton-Miner#1]
Is there a way to save the output from mining to a file as well as output to the screen?

**Comment by scavicchio** [comment]
Yes. I am working on the next version which will provide output for some statistics and monitoring.

**Comment by redrocketgt** [comment]
Great. 

It would also be nice to allow user to set of threads in case they don't wan't 100% CPU usage.
Take out --mine from the script and either issue miner.start() ie use all threads or miner.start(x) ie uses x threads.

**Comment by scavicchio** [comment]
You can change the number of threads by setting the affinity in task manager, but I will also include an implementation in the next release!

**Comment by scavicchio** [comment]
New update creates a log of hashrate over time. Also gives many configuration options
