### ISSUE TITLE
EasyWaltonMiner.exe not running. I can see a cmd window open and immediately closes within 0.1s.

### ISSUE THREAD

**Issue by Sinfularoma** [scavicchio/Easy-Walton-Miner#2]
What I got when running the exe through cmd

Error loading Python DLL 'C:\Users\Admin\Desktop\easyWaltonMiner\python36.dll'. LoadLibrary: The specified module could not be found.

Tried on windows 8.1, Windows 10, ran the exe and and see a cmd pop up and closes within 0.1sec, tried to run as administrator too.

Tried on ryzen 1700, i7 4770, i7 6700

No problem with the Lite Version.

**Comment by scavicchio** [comment]
Is is possible that instead of making a shortcut to the easyWaltonMiner.exe, you accidentially copied the exe to the desktop? This would cause this error since it is looking for the python36.dll file that is in the folder with the rest of the files, and not in the desktop.

**Comment by scavicchio** [comment]
Pre-compiled EXE now added to release. Just extract and double click the easyWaltonMiner.exe to run!
