### ISSUE TITLE
Error Loading Module 

### ISSUE THREAD

**Issue by ice578** [scavicchio/Easy-Walton-Miner#3]
I get the following error after executing it in Command prompt:

Error loading Python DLL 'C:\Users\X\Desktop\easyWaltonMiner-v1.3\easyWalto
nMiner\python36.dll'.
LoadLibrary: The specified module could not be found.

**Comment by scavicchio** [comment]
This error is a result of copying the easyWaltonMiner.exe to the desktop instead of making a shortcut. To remedy, copy the easyWaltonMiner.exe back to the original program file, and right click on the exe to select "send to->Desktop" to make the shortcut.
