### ISSUE TITLE
improvement: possiblity to log mined blocks

### ISSUE THREAD

**Issue by dasraab** [scavicchio/Easy-Walton-Miner#4]
HI there and first of all thanks for this great tool!

I´m searching for a way to log when a node has mined a block. Is it possible to append to a logfile whenever a block is mined?

We could use this information to, for example, send a telegram message via webhook or fill a database and create mining statistics etc.

i´m not a windows user so i´ve no clue how to get this information out of the windows command window to be honest.

do you have any ideas?

**Comment by scavicchio** [comment]
Hi dasraab, Sorry for the late reply. In your file, add --extradata "XXX" to the walton function call (this is either in the batch file or the easyWaltonTracker.py file depending on which version you are using). This will add the data to the blockchain with you can check later. I am working on a program to view all this data right now.
