### ISSUE TITLE
 dial tcp 127.0.0.1:12125: connectex: No connection could be made because the target machine actively refused it.

### ISSUE THREAD

**Issue by squintzMcgee** [scavicchio/Easy-Walton-Miner#5]
Cannot for the life of me get this to work using the full version and gpu lite.. any suggestions?

**Comment by squintzMcgee** [comment]
SOLVED: For whatever reason, I think I needed to run the miner in the WTC wallet in order to get the private / public network option for windows firewall to popup so I could select it. After that it fired up fine. Thanks!

**Comment by scavicchio** [comment]
Nice! Glad it worked out. +1 for solving it for me haha.
